apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10