apiVersion: v1
kind: Service
metadata:
  name: python-api
  labels:
    app: python-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: python-api
